In [2]:
import csv

from google.colab import files
uploaded = files.upload()

Saving wildfire_data.csv to wildfire_data.csv

In [3]:
uploaded = files.upload()

Saving 주요관광지점 입장객_2.xls to 주요관광지점 입장객_2.xls

In [5]:
import pandas as pd
df = pd.read_csv("wildfire_data.csv")
df

,Unnamed: 0,region,date,wildfire,ave_temp,min_temp,max_temp,max_windspeed,ave_windspeed,rel_humidity,population_density,softwood_area,hardwood_area,mixedforest_area
0,0,강릉시,2012-01-01,0,0.8,-1.8,4.5,5.7,2.5,51.3,2.177654e-47,0.360171,0.326828,0.295208
1,1,고성군,2012-01-01,0,1.1,-1.5,4.9,5.7,2.2,44.8,2.875464e-48,0.285251,0.398403,0.238032
2,2,동해시,2012-01-01,0,1.6,-1.1,5.3,5.5,3.2,50.1,9.183948e-48,0.367967,0.346120,0.259024
3,3,삼척시,2012-01-01,0,1.6,-1.1,5.3,5.5,3.2,50.1,6.479098e-48,0.440111,0.292338,0.236507
4,4,속초시,2012-01-01,0,1.1,-1.5,4.9,5.7,2.2,44.8,8.477622e-48,0.248219,0.327834,0.328709
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65855,65855,태백시,2021-12-31,0,-9.9,-12.8,-5.6,4.0,1.8,31.5,4.155931e-48,0.348856,0.407704,0.182570
65856,65856,평창군,2021-12-31,0,-11.8,-14.7,-7.3,10.3,5.6,37.9,4.193048e-48,0.320343,0.431395,0.215337
65857,65857,홍천군,2021-12-31,0,-7.3,-11.7,-3.1,4.1,1.7,37.4,6.990233e-48,0.354997,0.385935,0.242038
65858,65858,화천군,2021-12-31,0,-9.1,-13.7,-4.6,3.5,1.5,42.5,2.470217e-48,0.189651,0.525684,0.275323
65859,65859,횡성군,2021-12-31,0,-5.6,-8.8,-2.4,4.1,1.6,31.6,4.769819e-48,0.380590,0.340259,0.239917

In [24]:
df_1 = pd.read_excel("주요관광지점 입장객_2.xls")
df_1

,시도,군구,관광지,내/외국인,총계(2012.01 ~ 2021.12),2012년,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 125,Unnamed: 126,Unnamed: 127,Unnamed: 128,Unnamed: 129,Unnamed: 130,Unnamed: 131,Unnamed: 132,Unnamed: 133,Unnamed: 134
0,NaN,NaN,NaN,NaN,NaN,인원계,2012년 01월,2012년 02월,2012년 03월,2012년 04월,...,2021년 03월,2021년 04월,2021년 05월,2021년 06월,2021년 07월,2021년 08월,2021년 09월,2021년 10월,2021년 11월,2021년 12월
1,강원도,춘천시,국립용화산자연휴양림,합계,681050.0,73644,2600,1500,1700,1859,...,1606,3221,8580,6624,12758,14117,8990,8861,6212,3932
2,강원도,원주시,백운산자연휴양림,합계,927367.0,110695,7682,5586,5725,7379,...,3261,4511,7038,10462,15288,17936,13137,13991,6662,3305
3,강원도,원주시,치악산 국립공원,합계,533771.0,533771,27825,23830,28071,28225,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,강원도,원주시,치악산자연휴양림,합계,325022.0,24213,1257,1304,1181,1460,...,2903,3687,5943,4923,5641,4998,4716,5436,4554,4203
5,강원도,강릉시,오대산국립공원소금강,합계,1165086.0,175362,2548,2388,2541,7128,...,1299,2780,4171,3122,4357,4579,4694,14537,6697,1587
6,강원도,태백시,태백산국립공원,합계,5711495.0,624952,226388,158855,22143,14642,...,16456,18241,30800,30314,48105,49184,25415,28537,22085,20788
7,강원도,속초시,설악산국립공원(설악동),합계,21061220.0,2718625,165596,123209,142762,205828,...,50897,105141,75638,109682,100931,111011,103976,251104,144111,81795
8,강원도,홍천군,가리산자연휴양림,합계,388584.0,50414,2616,3683,4279,3473,...,3438,415,550,378,9075,10215,6459,781,384,272
9,강원도,홍천군,팔봉산관광지,합계,612431.0,75017,0,0,3626,7482,...,2500,4188,5025,4239,2509,3206,3890,5163,3432,247
10,강원도,횡성군,청태산자연휴양림,합계,164117.0,164117,10237,8654,7759,7635,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,강원도,평창군,계방산(평창군),합계,655043.0,100655,20118,14198,745,34,...,57,3,1540,2452,2313,2614,1932,3500,1025,3457
12,강원도,평창군,국립두타산자연휴양림,합계,429601.0,47867,1046,1043,2234,1762,...,0,0,0,25,8363,9768,6036,6822,91,1836
13,강원도,평창군,백덕산(평창군),합계,48252.0,NaN,NaN,NaN,NaN,NaN,...,993,978,1588,1235,810,1010,1271,1460,876,858
14,강원도,평창군,오대산국립공원(월정사),합계,10469388.0,1109779,75532,64091,35509,62773,...,16128,25057,39607,37010,48152,63007,36920,148018,86288,48925
15,강원도,정선군,가리왕산자연휴양림,합계,748515.0,76140,2983,1993,1801,2728,...,2755,3783,9252,10231,17551,20779,11057,12499,4798,2672
16,강원도,정선군,민둥산,합계,462155.0,462155,1300,1205,1500,1550,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,강원도,철원군,복주산자연휴양림,합계,396319.0,42117,3005,2264,2049,2526,...,1543,1408,2938,3539,5746,5558,4137,5135,3298,2694
18,강원도,인제군,방태산 자연 휴양림,합계,64198.0,64198,2702,2607,1673,1114,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,강원도,인제군,점봉산곰배령,합계,544166.0,NaN,NaN,NaN,NaN,NaN,...,0,3964,13917,12370,9383,8796,7304,14047,10,505
20,강원도,양양군,설악산 국립공원 오색지구,합계,434553.0,434553,11641,9210,7893,17198,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Warning: Total number of columns (135) exceeds max_columns (20) limiting to first (20) columns.

0         인원계
1       73644
2      110695
3      533771
4       24213
5      175362
6      624952
7     2718625
8       50414
9       75017
10     164117
11     100655
12      47867
13        NaN
14    1109779
15      76140
16     462155
17      42117
18      64198
19        NaN
20     434553
Name: 2012년, dtype: object